package ws.crossnet.apn.vuce.vucentws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-04-27T21:20:23.501-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", name = "VucentWSPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface VucentWSPortType {

    @WebMethod(action = "urn:sincronizarTablas")
    @Action(input = "urn:sincronizarTablas", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/sincronizarTablasResponse")
    @RequestWrapper(localName = "sincronizarTablas", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.SincronizarTablas")
    @ResponseWrapper(localName = "sincronizarTablasResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.SincronizarTablasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sincronizarTablas(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad,
        @WebParam(name = "xmlMensaje", targetNamespace = "")
        javax.activation.DataHandler xmlMensaje,
        @WebParam(name = "xmlTablas", targetNamespace = "")
        javax.activation.DataHandler xmlTablas
    );

    @WebMethod(action = "urn:obtenerTransaccionesPendientesConLimite")
    @Action(input = "urn:obtenerTransaccionesPendientesConLimite", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/obtenerTransaccionesPendientesConLimiteResponse")
    @RequestWrapper(localName = "obtenerTransaccionesPendientesConLimite", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerTransaccionesPendientesConLimite")
    @ResponseWrapper(localName = "obtenerTransaccionesPendientesConLimiteResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerTransaccionesPendientesConLimiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<javax.activation.DataHandler> obtenerTransaccionesPendientesConLimite(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.Integer idEntidad,
        @WebParam(name = "tipoTransacciones", targetNamespace = "")
        java.util.List<java.lang.String> tipoTransacciones,
        @WebParam(name = "limite", targetNamespace = "")
        java.lang.Integer limite
    );

    @WebMethod(action = "urn:obtenerTransaccionesPendientes")
    @Action(input = "urn:obtenerTransaccionesPendientes", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/obtenerTransaccionesPendientesResponse")
    @RequestWrapper(localName = "obtenerTransaccionesPendientes", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerTransaccionesPendientes")
    @ResponseWrapper(localName = "obtenerTransaccionesPendientesResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerTransaccionesPendientesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<javax.activation.DataHandler> obtenerTransaccionesPendientes(
        @WebParam(name = "idEntidad", targetNamespace = "")
        java.lang.Integer idEntidad
    );

    @WebMethod(action = "urn:obtenerErroresEnvioTransmisiones")
    @Action(input = "urn:obtenerErroresEnvioTransmisiones", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/obtenerErroresEnvioTransmisionesResponse")
    @RequestWrapper(localName = "obtenerErroresEnvioTransmisiones", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerErroresEnvioTransmisiones")
    @ResponseWrapper(localName = "obtenerErroresEnvioTransmisionesResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerErroresEnvioTransmisionesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<javax.activation.DataHandler> obtenerErroresEnvioTransmisiones(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad
    );

    @WebMethod(action = "urn:enviarNotificaciones")
    @Action(input = "urn:enviarNotificaciones", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/enviarNotificacionesResponse")
    @RequestWrapper(localName = "enviarNotificaciones", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.EnviarNotificaciones")
    @ResponseWrapper(localName = "enviarNotificacionesResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.EnviarNotificacionesResponse")
    public void enviarNotificaciones(
        @WebParam(name = "xmlNotificacion", targetNamespace = "")
        javax.activation.DataHandler xmlNotificacion,
        @WebParam(name = "ebXML", targetNamespace = "")
        javax.activation.DataHandler ebXML,
        @WebParam(name = "adjuntos", targetNamespace = "")
        javax.activation.DataHandler adjuntos
    );

    @WebMethod(action = "urn:confirmarRecepcionMensaje")
    @Action(input = "urn:confirmarRecepcionMensaje", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/confirmarRecepcionMensajeResponse")
    @RequestWrapper(localName = "confirmarRecepcionMensaje", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ConfirmarRecepcionMensaje")
    @ResponseWrapper(localName = "confirmarRecepcionMensajeResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ConfirmarRecepcionMensajeResponse")
    public void confirmarRecepcionMensaje(
        @WebParam(name = "idTransaccion", targetNamespace = "")
        int idTransaccion,
        @WebParam(name = "error", targetNamespace = "")
        int error,
        @WebParam(name = "errores", targetNamespace = "")
        java.lang.String errores
    );

    @WebMethod(action = "urn:obtenerLiquidacionPagos")
    @Action(input = "urn:obtenerLiquidacionPagos", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/obtenerLiquidacionPagosResponse")
    @RequestWrapper(localName = "obtenerLiquidacionPagos", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerLiquidacionPagos")
    @ResponseWrapper(localName = "obtenerLiquidacionPagosResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerLiquidacionPagosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<javax.activation.DataHandler> obtenerLiquidacionPagos(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad
    );

    @WebMethod(action = "urn:obtenerResultadoSincronizacionTablas")
    @Action(input = "urn:obtenerResultadoSincronizacionTablas", output = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/VucentWS/obtenerResultadoSincronizacionTablasResponse")
    @RequestWrapper(localName = "obtenerResultadoSincronizacionTablas", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerResultadoSincronizacionTablas")
    @ResponseWrapper(localName = "obtenerResultadoSincronizacionTablasResponse", targetNamespace = "http://entidad.ws.remoting.ve.vuce.mincetur.gob.pe/", className = "ws.crossnet.apn.vuce.vucentws.ObtenerResultadoSincronizacionTablasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public javax.activation.DataHandler obtenerResultadoSincronizacionTablas(
        @WebParam(name = "idEntidad", targetNamespace = "")
        int idEntidad,
        @WebParam(name = "idProcesoSincronizacion", targetNamespace = "")
        int idProcesoSincronizacion
    );
}
